version: '3.8'

services:
  backend:
    image: kinyura/geubddong
    container_name: backend-app
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
